### PR TITLE
Add support for canelex's keystrokes

### PR DESCRIPTION
**Pull request by gepbird**
You can toggle the visibility of Canelex's Keystrokes mod.

### CODE REVIEW

**Comment by DJtheRedstoner** [comment]
Sorry, I completely forgot about this pr, I will test and merge first thing tomorrow!

**Comment by gepbird** [comment]
Hey, it's been almost a week, can you review this PR?

**Comment by FacioZMafii** [comment]
lazy

**Comment by proudmuslim-dev** [comment]
dj best repo maintainer

**Comment by FacioZMafii** [comment]
agreed

**Comment by FacioZMafii** [comment]
finally after 1 month

**Pull request merged**
