### PR TITLE
Mod should be ubuntu i need ubuntu mod please ubuntu mod

### PR DESCRIPTION
**Pull request by UnderscoreUnderscoreBreezy**
If i dont get ubuntu mod i will piss and probably shit

### CODE REVIEW

**Comment by DJtheRedstoner** [comment]
gruh

**Review by proudmuslim-dev — COMMENTED** [review]
I approve

**Review by TymanWasTaken — COMMENTED** [review]
Same

**Review by FacioZMafii — COMMENTED** [review]
yes

**Pull request closed without merging**
