### PR TITLE
Ported to all minecraft versions.

### PR DESCRIPTION
**Pull request by Debuggingss**
Many gamers prefer older or newer versions of the game for the best experience.

### CODE REVIEW

**Comment by Antonio32A** [comment]
:clown_face:

**Comment by Debuggingss** [comment]
> 🤡

At least I contributed to his repository by porting it to all mc versions.

**Comment by DJtheRedstoner** [comment]
I only accept contributions in the form of lzma compressed, gizped, patch files at this moment. Sorry for any inconvenience.

**Comment by Debuggingss** [comment]
> I only accept contributions in the form of lzma compressed, gizped, patch files at this moment. Sorry for any inconvenience.

Okay

**Pull request closed without merging**
